def main():
    try:
        x = 1/0
    except:
        print('there was an error')

main()
